version: "3.4"
services:
  spark-posts-service:
    image: sparkpost
    build: 
      context: .
    depends_on: 
    - mongo
    ports:
    - "3000:3000"
    environment: 
    - MONGO_URI=mongodb://mongo:27017/spark
    - PORT=3000
  mongo:
    image: mongo
    ports: 
    - "27017:27000"